initialize RFC process
hyprwm/RFCs pull request #1
Opened 2024-05-01 21:41 UTC by NotAShelf

Formally initiates the RFC process for Hyprwm. Motivations for this initiative, and an outline of the process are both included in the initial draft.

2024-05-01 22:22 UTC, vaxerski reviewed
h

2024-05-02 01:26 UTC, yavko approved these changes
I think this is great, but I had one thought, and I may be reading this wrong, but you say that some things cannot be changed like C++, and some may be difficult to change. However, I see a small problem with this, since vaxry is the one who essentially runs hyprland and is the BDFL, I think there may be a rare case where the community wants a change that vaxry doesn't, how is that resolved? Like does vaxry have the final say? Since here's how I see it, if the steering committee merges a PR, let's say to change the build system; which you say should be really difficult. What happens after that, is vaxry now required to implement it even if he doesn't want to. I feel like this should be explicitly defined.

2024-05-03 17:24 UTC, vaxerski approved these changes

2024-05-04 01:44 UTC, yavko requested changes

2024-05-04 17:40 UTC, yavko approved these changes

2024-05-04 18:10 UTC, fufexan approved these changes

2024-05-04 19:44 UTC, merged